### ISSUE TITLE
GGIS viewers checklist

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#203]
Hi @ArnaudIGRAC @clau1313 @alexia  I made this checklist to mark out the map viewer that have been completed and those are not. If you need me to complete some of the viewers, please let me know and I will get onto  them. I left out the viewers highlighted in gray from the word document.

- [x] MAR Portal - Seabilwe
- [x] Transboundary Aquifers of the World - Seabilwe
- [x] Senegalo-Mauritanian Aquifer Basin - Seabilwe
- [x] Groundwater for refugees - Seabilwe
- [x] Groundwater quality - Seabilwe
- [x] GGMN Portal - Seabilwe
- [x] Dinaric Karst (DIKTAS Project) - Seabilwe 
- [x] Transboundary Aquifers (TWAP Project) - Seabilwe
- [x] Global Country Data - Seabilwe
- [x] Small Island Developing States (TWAP) - Seabilwe
- [x] Groundwater Resources in Africa - Seabilwe
