### ISSUE TITLE
[EPIC] Completion plan

### ISSUE THREAD

**Issue by timlinux** [kartoza/IGRAC-GGIS#204]
Jan 14 2021

Site launch for IGRAC

- [x] GGMN data migration - @dimasciput  for Tuesday 8
- [x] Well form
- [x] Well map
- [x] Batch upload & data checks
- [x] Layers
- [x] Maps
- [x] Documents - Final backup from old website

No cost extension:

* Mobile app
* Canada data feed integration
* Manual / Documentation
* Translation framework (French & Spanish) using transifex
