### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#509]
The features:
- [x] Geostory, as well as upgrading geonode to version 3 : https://github.com/kartoza/IGRAC-GGIS/issues/504
- [x] 1 Change permission level : #487 
- [x] 2 Update download feature : #488
- [x] 3 Remove upload button : #489 
- [x] 5 Registration updates : #490

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, please don't forget #476 before moving to production.
