### ISSUE TITLE
[EPIC] Upgrade to geonode 4.x

### ISSUE THREAD

**Issue by meomancer** [kartoza/IGRAC-GGIS#534]
# Problem
We need to upgrade geonode to latest version

# Solution
- [x] Revert all of deployment to use latest geonode deployment (currently is using spc geonode)
- [x] Put current custom igrac link to latest navbar :https://github.com/kartoza/IGRAC-GGIS/issues/532
- [x] Customize landing page : https://github.com/kartoza/IGRAC-GGIS/issues/533
- [x] Keep current igrac app, gwml2, and it's settings
- [x] Put https://github.com/kartoza/IGRAC-WellAndMonitoringDatabase/blob/7f299980a4c1c135d7466b9aba254f1ee8620605/management/commands/update_fixtures.py to entrypoint of container

**Comment by ArnaudIGRAC** [comment]
Hi Dimas, here are already a few comments, I will maybe send you a few more next Monday.
1. reshuffle the two menu bars as follow
![image](https://user-images.githubusercontent.com/64771599/228884419-a27f33fb-686b-486c-8139-af4682ae9a2b.png)
3. Use same IGRAC logo as before, this one is darker. 
4. Expand filters per default 
5. In the filters, replace "Datasets" with "Map layers"
6. is it possible to see your name next to your profile picture, as in current version? 
![image](https://user-images.githubusercontent.com/64771599/228804634-305eea5b-9aa1-42f7-a5dc-fd749ccca5fe.png)
7. The profile button doesn't work when in a slug map.
8. In the admin, would it be possible to rename "GWML2" with "Well and Monitoring Data"
9. Use the same font as in current GGIS. See difference here for example
![image](https://user-images.githubusercontent.com/64771599/228887349-db05fee1-e315-45a1-bfc1-a91479e8fc88.png)
![image](https://user-images.githubusercontent.com/64771599/228887426-206d841a-5e75-4e39-85c2-d5bd9f39a3ff.png)
10. When you hover over the field Monitoring Data, in the database, you can't read it anymore. Please use the same fonts, color and symbology as before.
![image](https://user-images.githubusercontent.com/64771599/228888975-03dc5717-244b-4d3c-83b2-a544f5c18e45.png)
11. The fields are also messed up (not properly aligned as before)
![image](https://user-images.githubusercontent.com/64771599/228889681-7ba2658e-12aa-4277-a9d7-2addd7ea2b74.png)
13. Also the search bar (there is a square inside)
![image](https://user-images.githubusercontent.com/64771599/228889793-13067fe5-ad2f-4cce-b64d-f177a0f8e3dc.png)


I am not convinced with the double top bar, is there a reason for that? Would there be a chance to change that in the future?

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
I have fixed the checked one
I need @dimasciput helps for the unchecked one, because it is coming from mapstore

> I am not convinced with the double top bar, is there a reason for that? Would there be a chance to change that in the future?

I have fixed to just have 1 top bar

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan and Dimas, it looks very nice! I noticed two other things:
- [ ] In the Well and Monitoring Data record forms, when you click on the tab "Management", "Hydrogeology" gets highlighted. When you click on "Groundwater levels", "Management" gets highlighted. 
- [ ] Also in the Well and Monitoring Data record forms, the top bar is modified: the home logo is very small and there is a box inside the search bar. The font of the menu item looks smaller
Please put the website in production once these two issues have been addressed

**Comment by meomancer** [comment]
thank you @ArnaudIGRAC 
I will address it on Friday, and release it to production after that
